steps:
  - step: "Inicialização"
    actions:
      - action: "Atualizando cache dos repositórios"
        command: "sudo apt update -y"
      - action: "Atulizando estatísticas"
        command: "sudo apt update -y"
      - action: "Atualizando pacotes existentes"
        command: "sudo apt upgrade -y"
      - action: "Atualizando distribuição"
        command: "sudo apt dist-upgrade -y"
  - step: "Adicionando Repositórios"
    actions:
      - action: "Adicionado PPA FileZilla"
        command: "sudo add-apt-repository ppa:sicklylife/filezilla -y"
      - action: "Adicionado PPA Tor Browser"
        command: "sudo add-apt-repository ppa:micahflee/ppa -y"
      - action: "Adicionando PPA OBS studio"
        command: "sudo add-apt-repository ppa:obsproject/obs-studio -y"
      - action: "Adicionando Repo NodeJS 14.x"
        command: "curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -"
      - action: "Adicionando  Repo Yarn"
        command: "curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null && echo 'deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"
      - action: "Atuaizando cache dos repositórios"
        command: "sudo apt update -y"
  - step: "Instalando Pacotes"
    actions:
      - action: "FIleZilla"
        command: "sudo apt-get install filezilla -y"
      - action: "AutoKey"
        command: "sudo apt-get install autokey-gtk -y"
      - action: "Telegram"
        command: "sudo apt install telegram-desktop -y"
      - action: "Flameshot"
        command: "sudo apt install flameshot -y"
      - action: "Tor Browser"
        command: "sudo apt install torbrowser-launcher -y"
      - action: "OBS Studio"
        command: "sudo apt install obs-studio -y"
      - action: "ZSH for Gnome-Terminal"
        command: "sudo apt install zsh -y"
      - action: "Git"
        command: "sudo apt install git -y"
      - action: "Wget"
        command: "sudo apt install wget -y"
      - action: "Curl"
        command: "sudo apt install curl -y"
      - action: "CIFS"
        command: "sudo apt install cifs-utils -y"
      - action: "Samba"
        command: "sudo apt install samba -y"
      - action: "Rar"
        command: "sudo apt install rar -y"
      - action: "Unrar"
        command: "sudo apt install unrar -y"
      - action: "IFconfig | Route | Net-tools"
        command: "sudo apt install net-tools -y"
      - action: "PHP7.4"
        command: "sudo apt install -y php php-cli php-fpm php-json php-common php-mysql php-zip php-gd php-mbstring php-curl php-xml php-pear php-bcmath"
      - action: "NodeJS 14.x"
        command: "sudo apt -y install nodejs"
      - action: "Yarn"
        command: "sudo apt install yarn -y"
      - action: "Dev-tools | GCC | G++ | make"
        command: "sudo apt -y install gcc g++ make"
      - action: "Fira Code"
        command: "sudo apt install fonts-firacode -y"
      - action: "Gnome-Tweaks"
        command: "sudo apt install gnome-tweak-tool -y"
  - step: "Instalando Snaps"
    actions:
      - action: "WhatsApp"
        command: "sudo snap install whatsapp-for-linux"
      - action: "VS Code"
        command: "sudo snap install --classic code"
      - action: "Spotfy"
        command: "snap install spotify"
  - step: "Instalando Flatpaks"
    actions:
      - action: "Aposthrofe"
        command: "flatpak install https://flathub.org/repo/appstream/org.gnome.gitlab.somas.Apostrophe.flatpakref"
      - action: "Markets"
        command: "flatpak install https://flathub.org/repo/appstream/com.bitstower.Markets.flatpakref"
      - action: "Blanket"
        command: "flatpak install https://flathub.org/repo/appstream/com.rafaelmardojai.Blanket.flatpakref"
  - step: "Instalando arquivos .deb"
    actions:
      - action: "Chrome DEV Channel"
        command: "wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb -O chrome.deb && sudo dpkg -i chrome.deb && sudo apt install -f"
  - step: "Instalando pacotes Yarn globalmente"
    actions:
      - action: "ReactJS | create-react-app"
        command: "yarn global add create-react-app"
      - action: "React Native | Expo-CLI"
        command: "yarn global add expo-cli"
  - step: "Realizando limpeza"
    actions:
      - action: "Refatorando pacotes e repositórios"
        command: "sudo dpkg --configure -a && sudo apt install --fix-missing"
      - action: "Limpando instalções"
        command: "sudo apt clean"
      - action: "Removendo pacotes desnecessários"
        command: "sudo apt remove && sudo apt auto-remove"
      - action: "Atualizando tudo"
        command: "sudo apt update && sudo apt upgrade && sudo apt dist-upgrade"